<?php
/**
 * @package modules
 * @copyright (C) 2002-2009 The Digital Development Foundation
 * @license GPL {@link http://www.gnu.org/licenses/gpl.html}
 * @link http://www.xaraya.com
 *
 * @subpackage roles
 * @link http://xaraya.com/index.php/release/27.html
 */
/* Include the base class */
sys::import('modules.dynamicdata.class.properties');
/**
 * Handle Social Profiles property
 * @author mikespub <mikespub@xaraya.com>
 */
class SocialProfilesProperty extends DataProperty
{
    public $id         = 2828;
    public $name       = 'socialprofiles';
    public $desc       = 'Social Profiles';
    public $reqmodules = array('roles');

// TODO: make available profiles configurable

    function __construct(ObjectDescriptor $descriptor)
    {
        parent::__construct($descriptor);
        $this->tplmodule = 'roles';
        $this->template = 'socialprofiles';
        $this->filepath = 'modules/roles/xarproperties';
    }

    public function checkInput($name = '', $value = null)
    {
        $name = empty($name) ? 'dd_'.$this->id : $name;
        // store the fieldname for validations who need them (e.g. file uploads)
        $this->fieldname = $name;

        if (!isset($value)) {
            if (!xarVarFetch($name, 'array', $value, array(), XARVAR_NOT_REQUIRED)) return;
            $cleanval = array();
            foreach (array_keys($value) as $site) {
                foreach ($value[$site] as $key => $val) {
                    if (empty($val)) continue;
                    $cleanval[$site][$key] = $val;
                }
            }
            $value = $cleanval;
        }
        return $this->validateValue($value);
    }

    public function validateValue($value = null)
    {
        if (!parent::validateValue($value)) return false;

        if (!is_array($value)) {
            $this->value = null;
            return false;
        }
        $this->setValue($value);
        return true;
    }

    function setValue($value=null)
    {
        if (!empty($value) && !is_array($value)) {
            $this->value = $value;
        } else {
            if (empty($value)) $value = array();
            $this->value = serialize($value);
        }
    }

    public function getValue()
    {
        try {
            $value = unserialize($this->value);
        } catch(Exception $e) {
            $value = array();
        }
        return $value;
    }

    public function showInput(Array $data = array())
    {
        if (!isset($data['value'])) $data['value'] = $this->getValue();
        $data['profiles'] = $this->getProfiles();
        return parent::showInput($data);
    }

    public function showOutput(Array $data = array())
    {
        if (!isset($data['value'])) $data['value'] = $this->getValue();

        $data['links'] = array();
        $profiles = $this->getProfiles();
        foreach ($profiles as $profile) {
            $site = $profile[0];
            if (isset($data['value'][$site])) {
                $link = $profile[2];
                $search = array();
                $replace = array();
                foreach ($profile[3] as $var) {
                    if (!empty($data['value'][$site][$var])) {
                        $search[] = '{' . $var . '}';
                        $replace[] = $data['value'][$site][$var];
                    }
                }
                $link = str_replace($search,$replace,$link);
                $data['links'][] = array('site'    => $profile[0],
                                         'url'     => $profile[1],
                                         'profile' => $link,
                                         'icon'    => $profile[5]);
            }
        }
        return parent::showOutput($data);
    }

    public function getProfiles()
    {
        // Format:
        //    (site,
        //     url,
        //     profile,
        //     variables,
        //     order,
        //     icon)
        $profiles = array(
            array('StumbleUpon',
                  'http://www.stumbleupon.com/',
                  'http://{username}.stumbleupon.com/',
                  array('username'),
                  1,
                  'stumbleupon.png'),
            array('Twitter',
                  'http://www.twitter.com/',
                  'http://www.twitter.com/{username}',
                  array('username'),
                  2,
                  'twitter.png'),
            array('Plurk',
                  'http://www.plurk.com/',
                  'http://www.plurk.com/user/{username}/',
                  array('username'),
                  3,
                  'plurk.png'),
            array('Ma.gnolia',
                  'http://ma.gnolia.com/',
                  'http://ma.gnolia.com/people/{username}/',
                  array('username'),
                  4,
                  'magnolia.png'),
            array('Flickr',
                  'http://www.flickr.com/',
                  'http://www.flickr.com/photos/{username}/',
                  array('username'),
                  5,
                  'flickr.png'),
            array('Delicious',
                  'http://delicious.com/',
                  'http://delicious.com/{username}/',
                  array('username'),
                  6,
                  'delicious.png'),
            array('Facebook',
                  'http://www.facebook.com/',
                  'http://www.facebook.com/people/{name}/{userid}',
                  array('name','userid'),
                  7,
                  'facebook.png'),
            array('Friendfeed',
                  'http://friendfeed.com',
                  'http://friendfeed.com/{username}',
                  array('username'),
                  8,
                  'friendfeed.png'),
            array('Lifestream',
                  'http://lifestream.fm/',
                  'http://lifestream.fm/{username}',
                  array('username'),
                  9,
                  'lifestream.png'),
            array('LinkedIn',
                  'http://www.linkedin.com/',
                  'http://www.linkedin.com/in/{username}',
                  array('username'),
                  10,
                  'linkedin.png'),
            array('MySpace',
                  'http://www.myspace.com/',
                  'http://www.myspace.com/{username}',
                  array('username'),
                  11,
                  'myspace.png'),
            array('Sphinn',
                  'http://www.sphinn.com/',
                  'http://sphinn.com/user/view/profile/{username}/',
                  array('username'),
                  12,
                  'sphinn.png'),
            array('MyOpenId',
                  'http://www.myopenid.com/',
                  'http://{username}.myopenid.com/',
                  array('username'),
                  13,
                  'myopenid.png'),
            array('YouTube',
                  'http://www.youtube.com/',
                  'http://www.youtube.com/{username}',
                  array('username'),
                  14,
                  'youtube.png'),
            array('ThisNext',
                  'http://www.thisnext.com/',
                  'http://www.thisnext.com/by/{username}/',
                  array('username'),
                  15,
                  'thisnext.png'),
            array('Digg',
                  'http://digg.com/',
                  'http://digg.com/users/{username}/',
                  array('username'),
                  16,
                  'digg.png'),
            array('ThinkAtheist',
                  'http://www.thinkatheist.com/',
                  'http://www.thinkatheist.com/profile/{username}/',
                  array('username'),
                  17,
                  'thinkatheist.png'),
            array('netlog',
                  'http://www.netlog.com/',
                  'http://www.netlog.com/{username}/',
                  array('username'),
                  18,
                  'netlog.png'),
            array('Barcodepedia',
                  'http://www.barcodepedia.com/',
                  'http://www.barcodepedia.com/users/{username}/',
                  array('username'),
                  19,
                  'barcodepedia.png'),
            array('Steam',
                  'http://steamcommunity.com/',
                  'http://steamcommunity.com/id/{username}/',
                  array('username'),
                  20,
                  'steam.png'),
            array('Last.fm',
                  'http://www.last.fm',
                  'http://www.last.fm/user/{username}',
                  array('username'),
                  21,
                  'lastfm.png'),
            array('Reddit',
                  'http://www.reddit.com/',
                  'http://www.reddit.com/user/{username}/',
                  array('username'),
                  22,
                  'reddit.png'),
            array('Furl',
                  'http://www.furl.net/',
                  'http://www.furl.net/member/{username}/',
                  array('username'),
                  23,
                  'furl.png'),
            array('Mister Wong',
                  'http://www.mister-wong.com/',
                  'http://www.mister-wong.com/user/{username}/',
                  array('username'),
                  24,
                  'misterwong.png'),
            array('Twine',
                  'http://www.twine.com/',
                  'http://www.twine.com/user/{username}/',
                  array('username'),
                  25,
                  'twine.png'),
            array('Wis.dm',
                  'http://wis.dm/',
                  'http://wis.dm/users/{userid}-{username}/',
                  array('userid','username'),
                  26,
                  'wisdm.png'),
            array('SWiK',
                  'http://swik.net/',
                  'http://swik.net/User:{username}/',
                  array('username'),
                  27,
                  'swik.png'),
            array('Squidoo',
                  'http://www.squidoo.com/',
                  'http://www.squidoo.com/lensmasters/{username}',
                  array('username'),
                  28,
                  'squidoo.png'),
            array('Simpy',
                  'http://www.simpy.com/',
                  'http://www.simpy.com/user/{username}',
                  array('username'),
                  29,
                  'simpy.png'),
            array('SEOmoz',
                  'http://www.seomoz.org/',
                  'http://www.seomoz.org/users/view/{username}/',
                  array('username'),
                  30,
                  'seomoz.png'),
            array('Newsvine',
                  'http://www.newsvine.com/',
                  'http://{username}.newsvine.com/',
                  array('username'),
                  31,
                  'newsvine.png'),
            array('Netvouz',
                  'http://www.netvouz.com/',
                  'http://www.netvouz.com/{username}/',
                  array('username'),
                  32,
                  'netvouz.png'),
            array('Faves',
                  'http://faves.com/',
                  'http://faves.com/users/{username}',
                  array('username'),
                  33,
                  'faves.png'),
            array('Diigo',
                  'http://www.diigo.com/',
                  'http://www.diigo.com/profile/{username}/',
                  array('username'),
                  34,
                  'diigo.png'),
            array('de.lirio.us',
                  'http://de.lirio.us/',
                  'http://de.lirio.us/profile.php/{username}/',
                  array('username'),
                  35,
                  'delirious.png'),
            array('BlinkList',
                  'http://www.blinklist.com/',
                  'http://www.blinklist.com/{username}/',
                  array('username'),
                  36,
                  'blinklist.png'),
            array('BibSonomy',
                  'http://www.bibsonomy.org/',
                  'http://www.bibsonomy.org/user/{username}',
                  array('username'),
                  37,
                  'bigsonomy.png'),
            array('MyBlogLog',
                  'http://www.mybloglog.com/',
                  'http://www.mybloglog.com/buzz/members/{username}/',
                  array('username'),
                  38,
                  'mybloglog.png'),
            array('bebo',
                  'http://www.bebo.com/',
                  'http://www.bebo.com/{username}/',
                  array('username'),
                  39,
                  'bebo.png'),
            array('Friendster',
                  'http://www.friendster.com/',
                  'http://profiles.friendster.com/{username}/',
                  array('username'),
                  40,
                  'friendster.png'),
            array('DOPPLR',
                  'http://www.dopplr.com/',
                  'http://www.dopplr.com/traveller/{username}/',
                  array('username'),
                  41,
                  'dopplr.png'),
            array('Jaiku',
                  'http://www.jaiku.com/',
                  'http://{username}.jaiku.com/',
                  array('username'),
                  42,
                  'jaiku.png'),
            array('Jumpcut',
                  'http://www.jumpcut.com/',
                  'http://www.jumpcut.com/{username}',
                  array('username'),
                  43,
                  'jumpcut.png'),
            array('LiveJournal',
                  'http://www.livejournal.com/',
                  'http://{username}.livejournal.com/',
                  array('username'),
                  44,
                  'ilivejournal.png'),
            array('Multiply',
                  'http://www.multiply.com/',
                  'http://{username}.multiply.com/',
                  array('username'),
                  45,
                  'multiply.png'),
            array('Netflix',
                  'http://www.netflix.com/',
                  'http://rss.netflix.com/QueueRSS?id={username}',
                  array('username'),
                  46,
                  'netflix.png'),
            array('Shelfari',
                  'http://www.shelfari.com/',
                  'http://www.shelfari.com/{username}',
                  array('username'),
                  47,
                  'shelfari.png'),
            array('SlideShare',
                  'http://www.slideshare.net/',
                  'http://www.slideshare.net/{username}/',
                  array('username'),
                  48,
                  'slideshare.png'),
            array('Technorati',
                  'http://www.technorati.com/',
                  'http://www.technorati.com/people/technorati/{username}/',
                  array('username'),
                  48,
                  'technorati.png'),
            array('The DJ List',
                  'http://www.thedjlist.com/',
                  'http://www.thedjlist.com/djs/{username}/',
                  array('username'),
                  49,
                  'thedjlist.png'),
            array('Upcoming',
                  'http://upcoming.yahoo.com/',
                  'http://upcoming.yahoo.com/user/{username}/',
                  array('username'),
                  50,
                  'upcoming.png'),
            array('Wakoopa',
                  'http://wakoopa.com/',
                  'http://wakoopa.com/{username}/',
                  array('username'),
                  51,
                  'wakoopa.png'),
            array('Yelp',
                  'http://www.yelp.com/',
                  'http://www.yelp.com/user_details?userid={username}',
                  array('username'),
                  52,
                  'yelp.png'),
            array('Zorpia',
                  'http://www.zorpia.com/',
                  'http://www.zorpia.com/{username}/',
                  array('username'),
                  53,
                  'zorpia.png'),
            array('BlogMarks',
                  'http://www.blogmarks.net/',
                  'http://www.blogmarks.net/user/{username}/',
                  array('username'),
                  54,
                  'blogmarks.png'),
            array('BlogMemes',
                  'http://www.blogmemes.com/',
                  'http://www.blogmemes.com/user/{username}',
                  array('username'),
                  55,
                  'blogmemes.png'),
            array('Blogosphere News',
                  'http://www.blogospherenews.com/',
                  'http://www.blogospherenews.com/user.php?login={username}',
                  array('username'),
                  56,
                  'blogospherenews.gif'),
            array('Blogsvine',
                  'http://www.blogsvine.com/',
                  'http://www.blogsvine.com/user/view/profile/{username}/',
                  array('username'),
                  57,
                  'blogsvine.png'),
            array('brightkite',
                  'http://brightkite.com/',
                  'http://brightkite.com/people/{username}/',
                  array('username'),
                  58,
                  'brightkite.png'),
            array('BUMPzee',
                  'http://www.bumpzee.com/',
                  'http://www.bumpzee.com/users/view/{username}/',
                  array('username'),
                  58,
                  'bumpzee.png'),
            array('Dailymotion',
                  'http://www.dailymotion.com/',
                  'http://www.dailymotion.com/{username}/',
                  array('username'),
                  59,
                  'dailymotion.png'),
            array('Clipmarks',
                  'http://www.clipmarks.com/clipper/Torley/',
                  'http://www.clipmarks.com/clipper/{username}/',
                  array('username'),
                  60,
                  'clipmarks.png'),
            array('Connotea',
                  'http://www.connotea.org/',
                  'http://www.connotea.org/wiki/User:{username}',
                  array('username'),
                  61,
                  'connotea.png'),
            array('Design Float',
                  'http://www.designfloat.com/',
                  'http://www.designfloat.com/user/view/profile/{username}/',
                  array('username'),
                  62,
                  'designfloat.gif'),
            array('DotNetKicks',
                  'http://www.dotnetkicks.com/',
                  'http://www.dotnetkicks.com/users/{username}/',
                  array('username'),
                  63,
                  'dotnetkicks.png'),
            array('DZone',
                  'http://www.dzone.com/',
                  'http://www.dzone.com/links/users/profile/{username}.html',
                  array('username'),
                  64,
                  'dzone.png'),
            array('eKudos',
                  'http://www.ekudos.nl/',
                  'http://www.ekudos.nl/gebruiker/{username}/',
                  array('username'),
                  65,
                  'ekudos.gif'),
            array('FARK',
                  'http://www.fark.com/',
                  'http://cgi.fark.com/cgi/fark/users.pl?login={username}',
                  array('username'),
                  66,
                  'fark.png'),
            array('Feed Me Links',
                  'http://www.feedmelinks.com/',
                  'http://www.feedmelinks.com/u/{username}/',
                  array('username'),
                  67,
                  'feedmelinks.png'),
            array('Fleck',
                  'http://www.fleck.com/',
                  'http://www.fleck.com/profile/{username}/',
                  array('username'),
                  68,
                  'fleck.gif'),
            array('Fleck',
                  'http://www.foodfeed.us/',
                  'http://{username}.foodfeed.us/',
                  array('username'),
                  69,
                  'foodfeed.png'),
            array('Global Grind',
                  'http://globalgrind.com/',
                  'http://globalgrind.com/user/{username}/',
                  array('username'),
                  70,
                  'globalgrind.gif'),
            array('Health Ranker',
                  'http://www.healthranker.com/',
                  'http://www.healthranker.com/user/view/profile/{username}/',
                  array('username'),
                  71,
                  'healthranker.gif'),
            array('HEMiDEMi',
                  'http://www.hemidemi.com/',
                  'http://www.hemidemi.com/user/{username}/',
                  array('username'),
                  72,
                  'hemidemi.png'),
            array('identi.ca',
                  'http://identi.ca/',
                  'http://identi.ca/{username}',
                  array('username'),
                  73,
                  'identica.png'),
            array('iLike',
                  'http://www.ilike.com/',
                  'http://www.ilike.com/user/{username}/',
                  array('username'),
                  74,
                  'ilike.png'),
            array('iliketotallyloveit',
                  'http://www.iliketotallyloveit.com/',
                  'http://www.iliketotallyloveit.com/user/{username}/',
                  array('username'),
                  75,
                  'iliketotallyloveit.png'),
            array('IndianPad',
                  'http://www.indianpad.com/',
                  'http://www.indianpad.com/user/{username}/',
                  array('username'),
                  76,
                  'indianpad.png'),
            array('joinR',
                  'http://www.joinr.de/',
                  'http://{username}.joinr.de/',
                  array('username'),
                  77,
                  'joinr.png'),
            array('Joost',
                  'http://www.joost.com/',
                  'http://www.joost.com/users/{username}/',
                  array('username'),
                  78,
                  'joost.png'),
            array('kirtsy',
                  'http://www.kirtsy.com/',
                  'http://www.kirtsy.com/user.php?login={username}',
                  array('username'),
                  79,
                  'kirtsy.gif'),
            array('KWICK',
                  'http://www.kwick.de/',
                  'http://www.kwick.de/{username}/',
                  array('username'),
                  80,
                  'kwick.png'),
            array('LinkARENA',
                  'http://linkarena.com/',
                  'http://{username}.linkarena.com/',
                  array('username'),
                  81,
                  'linkarena.gif'),
            array('BLOGTER',
                  'http://www.blogter.hu/',
                  'http://www.blogter.hu/index.php?action=view_profile&user_id={username}',
                  array('username'),
                  82,
                  'linkter.png'),
            array('Google Reader',
                  'http://www.google.com/',
                  'http://www.google.com/reader/shared/{username}',
                  array('username'),
                  83,
                  'googlereader.png'),
            array('men&eacute;ame',
                  'http://meneame.net/',
                  'http://meneame.net/user/{username}/',
                  array('username'),
                  84,
                  'meneame.png'),
            array('ebay',
                  'http://www.ebay.com/',
                  'http://myworld.ebay.com/{username}/',
                  array('username'),
                  85,
                  'ebay.png'),
            array('Mixx',
                  'http://www.mixx.com/',
                  'http://www.mixx.com/users/{username}',
                  array('username'),
                  86,
                  'mixx.png'),
            array('muti',
                  'http://www.muti.co.za/',
                  'http://www.muti.co.za/user?name={username}',
                  array('username'),
                  87,
                  'muti.png'),
            array('myvideo',
                  'http://www.myvideo.co.za/',
                  'http://www.myvideo.co.za/channels/{username}',
                  array('username'),
                  88,
                  'myvideo.png'),
            array('N4G',
                  'http://www.n4g.com',
                  'http://www.n4g.com/up/{username}.aspx',
                  array('username'),
                  89,
                  'n4g.gif'),
            array('Netvibes',
                  'http://www.netvibes.com/',
                  'http://www.netvibes.com/{username}',
                  array('username'),
                  90,
                  'netvibes.png'),
            array('Odeo',
                  'http://www.odeo.com/',
                  'http://www.odeo.com/users/{username}/',
                  array('username'),
                  91,
                  'odeo.png'),
            array('Photocase',
                  'http://www.photocase.com/',
                  'http://www.photocase.com/en/user.asp?u={username}',
                  array('username'),
                  92,
                  'photocase.png'),
            array('Picasaweb',
                  'http://picasaweb.google.com/',
                  'http://picasaweb.google.com/{username}/',
                  array('username'),
                  93,
                  'picasa.png'),
            array('Plazes',
                  'http://plazes.com/',
                  'http://plazes.com/users/{username}/',
                  array('username'),
                  94,
                  'plazes.png'),
            array('PlugIM',
                  'http://www.plugim.com/',
                  'http://www.plugim.com/user/{username}/',
                  array('username'),
                  95,
                  'plugim.png'),
            array('Polyvore',
                  'http://www.polyvore.com/',
                  'http://www.polyvore.com/cgi/profile?id={username}',
                  array('username'),
                  96,
                  'polyvore.png'),
            array('ppnow',
                  'http://www.ppnow.com/',
                  'http://www.ppnow.com/bookmark/{username}/',
                  array('username'),
                  97,
                  'ppnow.png'),
            array('Propeller',
                  'http://www.propeller.com/',
                  'http://www.propeller.com/member/{username}/',
                  array('username'),
                  98,
                  'propeller.png'),
            array('QIK',
                  'http://qik.com/',
                  'http://qik.com/{username}/',
                  array('username'),
                  99,
                  'qik.png'),
            array('Qype',
                  'http://www.qype.co.uk/',
                  'http://www.qype.co.uk/people/{username}/',
                  array('username'),
                  100,
                  'qype.png'),
            array('Ratimarks',
                  'http://www.ratimarks.org/',
                  'http://www.ratimarks.org/bookmarks.php/{username}/',
                  array('username'),
                  101,
                  'ratimarks.png'),
            array('Scoopeo',
                  'http://www.scoopeo.com/',
                  'http://www.scoopeo.com/membre/{username}/',
                  array('username'),
                  102,
                  'scoopeo.png'),
            array('Segnalo',
                  'http://segnalo.alice.it/',
                  'http://segnalo.alice.it/profile/{username}',
                  array('username'),
                  103,
                  'segnalo.gif'),
            array('Sevenload',
                  'http://www.sevenload.com/',
                  'http://www.sevenload.com/users/{username}',
                  array('username'),
                  104,
                  'sevenload.png'),
            array('Sixgroups',
                  'http://sixgroups.com/',
                  'http://sixgroups.com/profile/{username}/',
                  array('username'),
                  105,
                  'sixgroups.png'),
            array('Slashdot',
                  'http://slashdot.org/',
                  'http://slashdot.org/~{username}',
                  array('username'),
                  106,
                  'slashdot.png'),
            array('SmugMug',
                  'http://www.smugmug.com',
                  'http://{username}.smugmug.com/',
                  array('username'),
                  107,
                  'smugmug.png'),
            array('Folkd',
                  'http://www.folkd.com/',
                  'http://www.folkd.com/user/{username}/',
                  array('username'),
                  108,
                  'folkd.png'),
            array('tipjoy',
                  'http://tipjoy.com/',
                  'http://tipjoy.com/u/{username}/',
                  array('username'),
                  109,
                  'tipjoy.png'),
            array('Tumblr',
                  'http://www.tumblr.com/',
                  'http://{username}.tumblr.com/',
                  array('username'),
                  110,
                  'tumblr.png'),
            array('Twitxr',
                  'http://www.twitxr.com/',
                  'http://www.twitxr.com/{username}/',
                  array('username'),
                  111,
                  'twitxr.png'),
            array('uboot',
                  'http://www.uboot.com/',
                  'http://{username}.uboot.com/',
                  array('username'),
                  112,
                  'uboot.png'),
            array('Upnews',
                  'http://www.upnews.it/',
                  'http://www.upnews.it/user/view/profile/{username}/',
                  array('username'),
                  113,
                  'upnews.gif'),
            array('Venteria',
                  'http://venteria.com/',
                  'http://venteria.com/users/{username}/',
                  array('username'),
                  114,
                  'venteria.png'),
            array('Vimeo',
                  'http://www.vimeo.com/',
                  'http://www.vimeo.com/{username}/',
                  array('username'),
                  115,
                  'vimeo.png'),
            array('vi.sualize.us',
                  'http://vi.sualize.us/',
                  'http://vi.sualize.us/{username}/',
                  array('username'),
                  116,
                  'visualizeus.png'),
            array('Webride',
                  'http://webride.org/',
                  'http://webride.org/users/{username}/',
                  array('username'),
                  117,
                  'webride.png'),
            array('weheartit',
                  'http://www.weheartit.com/',
                  'http://www.weheartit.com/user/{username}/',
                  array('username'),
                  118,
                  'weheartit.png'),
            array('Wikipedia',
                  'http://www.wikipedia.org/',
                  'http://www.wikipedia.org/wiki/User:{username}',
                  array('username'),
                  119,
                  'wikipedia.png'),
            array('Wists',
                  'http://www.wists.com/',
                  'http://www.wists.com/{username}/',
                  array('username'),
                  120,
                  'wists.png'),
            array('Woobby',
                  'http://de.woobby.com/',
                  'http://de.woobby.com/user/profile?username={username}',
                  array('username'),
                  121,
                  'woobby.png'),
            array('xerpi',
                  'http://www.xerpi.com/',
                  'http://www.xerpi.com/profile/{username}/',
                  array('username'),
                  122,
                  'xerpi.gif'),
            array('Xing',
                  'http://www.xing.com/',
                  'http://www.xing.com/profile/{username}',
                  array('username'),
                  123,
                  'xing.png'),
            array('YiGG',
                  'http://www.yigg.de/',
                  'http://www.yigg.de/profil/{username}',
                  array('username'),
                  124,
                  'yigg.png'),
            array('Zooomr',
                  'http://www.zooomr.com/',
                  'http://www.zooomr.com/photos/{username}/',
                  array('username'),
                  125,
                  'zooomr.png'),
            array('Clipmarks',
                  'http://www.clipmarks.com/',
                  'http://www.clipmarks.com/clipper/{username}/',
                  array('username'),
                  126,
                  'zooomr.png'),
            array('Blogger',
                  'http://www.blogger.com/',
                  'http://www.blogger.com/profile/{username}',
                  array('username'),
                  127,
                  'blogger.png'),
            array('Goodreads',
                  'http://www.goodreads.com/',
                  'http://www.goodreads.com/profile/{userid}/',
                  array('userid'),
                  128,
                  'goodreads.png'),
            array('Disqus',
                  'http://www.disqus.com/',
                  'http://www.disqus.com/people/{username}/',
                  array('username'),
                  129,
                  'disqus.png'),
            array('Hi5',
                  'http://www.hi5.com/',
                  'http://www.hi5.com/friend/p{userid}--{username}--html',
                  array('userid','username'),
                  130,
                  'hi5.png'),
            array('ohloh',
                  'http://www.ohloh.net/',
                  'http://www.ohloh.net/accounts/{username}',
                  array('username'),
                  131,
                  'ohloh.png'),
            array('Writing.com',
                  'http://www.writing.com/',
                  'http://www.writing.com/main/view_item/user_id/{username}',
                  array('username'),
                  132,
                  'writing.png'),
            array('deviantART',
                  'http://www.deviantart.com/',
                  'http://{username}.deviantart.com/',
                  array('username'),
                  133,
                  'deviantart.png'),
            array('Blip.fm',
                  'http://blip.fm/',
                  'http://blip.fm/{username}/',
                  array('username'),
                  134,
                  'blipfm.png'),
            array('Blip.tv',
                  'http://blip.tv/',
                  'http://{username}.blip.tv/',
                  array('username'),
                  135,
                  'bliptv.png'),
            array('Windows Live',
                  'http://profile.live.com/',
                  'http://{userid}.profile.live.com/ ',
                  array('userid'),
                  136,
                  'livecom.png'),
            array('WAYN',
                  'http://www.wayn.com/',
                  'http://www.wayn.com/waynprofile.html?member_key={userid} ',
                  array('userid'),
                  137,
                  'wayncom.png'),
            array('Facebook Group',
                  'http://www.facebook.com/',
                  'http://www.facebook.com/group.php?gid={groupid}',
                  array('groupid'),
                  138,
                  'facebook.png'),
            array('Facebook Page',
                  'http://www.facebook.com/',
                  'http://www.facebook.com/pages/{pagename}/{pageid}',
                  array('pagename','pageid'),
                  139,
                  'facebook.png'),
            array('LinkedIn Company',
                  'http://www.linkedin.com/',
                  'http://www.linkedin.com/companies/{lkdncompanynameid}/{lkdncompanyname}',
                  array('lkdncompanynameid','lkdncompanyname'),
                  140,
                  'linkedin.png'),
            array('imeem',
                  'http://www.imeem.com/',
                  'http://www.imeem.com/{username}',
                  array('username'),
                  141,
                  'imeem.png'),
            array('12seconds',
                  'http://12seconds/',
                  'http://12seconds.tv/channel/{username}',
                  array('username'),
                  142,
                  '12secondstv.png'),
            array('Behance',
                  'http://www.behance.net/',
                  'http://www.behance.net/{username}',
                  array('username'),
                  143,
                  'behancenet.png'),
            array('LibraryThing',
                  'http://www.librarything.com/',
                  'http://www.librarything.com/profile/{username}',
                  array('username'),
                  144,
                  'librarythingcom.png'),
            array('LibraryThing Author',
                  'http://www.librarything.com/',
                  'http://www.librarything.com/author/{username}',
                  array('username'),
                  145,
                  'librarythingcom.png'),
            array('Facebook Profile',
                  'http://www.facebook.com/',
                  'http://www.facebook.com/{username}',
                  array('username'),
                  146,
                  'facebook.png'),
            array('Hyves',
                  'http://www.hyves.co.uk/',
                  'http://{username}.hyves.co.uk/',
                  array('username'),
                  147,
                  'hyvescom.png'),
            array('ClaimID',
                  'http://claimid.com/',
                  'http://claimid.com/{username}',
                  array('username'),
                  148,
                  'claimidcom.png'),
        );

        return $profiles;
    }
}
?>
