<?php
/*
 *  $Id: PgSQLPreparedStatement.php,v 1.14 2005/04/16 18:55:28 hlellelid Exp $
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the LGPL. For more information please see
 * <http://creole.phpdb.org>.
 */
 
require_once 'creole/PreparedStatement.php';
require_once 'creole/common/PreparedStatementCommon.php';

/**
 * PgSQL subclass for prepared statements.
 * 
 * @author Hans Lellelid <hans@xmpl.org>
 * @version $Revision: 1.14 $
 * @package creole.drivers.pgsql
 */
class PgSQLPreparedStatement extends PreparedStatementCommon implements PreparedStatement {
    
    /**
     * Quotes string using native pgsql function (pg_escape_string).
     * @param string $str
     * @return string
     */
    protected function escape($str)
    {
        return pg_escape_string($str);
    }
    
    // XARAYA MODIFICATION
    /**
     * Executes the SQL query in this PreparedStatement object and returns the resultset generated by the query.
     * We support two signatures for this method:
     * - $stmt->executeQuery(ResultSet::FETCHMODE_NUM);
     * - $stmt->executeQuery(array($param1, $param2), ResultSet::FETCHMODE_NUM);
     * @param mixed $p1 Either (array) Parameters that will be set using PreparedStatement::set() before query is executed or (int) fetchmode.
     * @param int $fetchmode The mode to use when fetching the results (e.g. ResultSet::FETCHMODE_NUM, ResultSet::FETCHMODE_ASSOC).
     * @return ResultSet
     * @throws SQLException if a database access error occurs.
     */
    public function executeQuery($p1 = null, $fetchmode = null)
    {    
        static $plan='';
        
        $params = null;
        if ($fetchmode !== null) {
            $params = $p1;
        } elseif ($p1 !== null) {
            if (is_array($p1)) $params = $p1;
            else $fetchmode = $p1;
        }
        
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        
        $this->updateCount = null; // reset
        $wouldBePlan = 'plan_'.md5($this->sql);
        if(!isset($this->conn->tobeplans[$wouldBePlan])) {
            // plan doesnt exist
            $this->conn->tobeplans[$wouldBePlan] = 1;
        } else {
            //xarLogMessage("CREOLE: Dupe SQL found BEFORE resolve: $this->sql");
        }
        
        $sql = $this->replaceParams();  
        
        if ($this->limit > 0 || $this->offset > 0) {
            $this->conn->applyLimit($sql, $this->offset, $this->limit);
        }
        
        $sql = $this->CheckPlanUsage($sql);

        $this->resultSet = $this->conn->executeQuery($sql, $fetchmode);
        return $this->resultSet;
    }
    
    /**
    * Executes the SQL INSERT, UPDATE, or DELETE statement in this PreparedStatement object.
     * 
     * @param array $params Parameters that will be set using PreparedStatement::set() before query is executed.
     * @return int Number of affected rows (or 0 for drivers that return nothing).
     * @throws SQLException if a database access error occurs.
     */
    public function executeUpdate($params = null) 
    {
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        
        if($this->resultSet) $this->resultSet->close();
        $this->resultSet = null; // reset 
        
        $wouldBePlan = 'plan_'.md5($this->sql);
        if(!isset($this->conn->tobeplans[$wouldBePlan])) {
            // plan doesnt exist
            $this->conn->tobeplans[$wouldBePlan] = 1;
        } else {
            //xarLogMessage("CREOLE: Dupe SQL found BEFORE resolve: $this->sql");
        }
        
        $sql = $this->replaceParams();  
        
        $sql = $this->CheckPlanUsage($sql);
        
        $this->updateCount = $this->conn->executeUpdate($sql);
        return $this->updateCount;
    }
    
    private function CheckPlanUsage($sql)
    {
        $useprepare=true;
        if($useprepare) {
            $newplan = 'plan_'.md5($sql);
            if(!isset($this->conn->plans[$newplan])) {
                // New plan, PREPARE it
                $prep = "PREPARE $newplan AS $sql";
                $prepped = pg_query($prep);
                if(!$prepped) {
                    throw new SQLException("Could not prepare query : $sql");
                }
                $this->conn->plans[$newplan] = 1;
            } else {
                //xarLogMessage("CREOLE: DUPE found : $sql");;
            }
            $sql = "EXECUTE $newplan";
        } 
        return $sql;
    }
    // END XARAYA MODIFICATION
    
    /**
     * Recursive function to turn multi-dim array into str representation.
     * @param array $arr
     * @return string Array in pgsql-friendly string notation: {val1, val2} or {{sub1,sub2}, {sub3, sub4}}
     */
    private function arrayToStr($arr)
    {
        $parts = array();
        foreach((array)$arr as $el) {
            if (is_array($el)) {
                $parts[] = $this->arrayToStr($el);
            } else {
                if (is_string($el)) {
                    $parts[] = '"' . pg_escape_string($el) . '"';
                } else {
                    $parts[] = $el;
                }                
            }
        }        
        return '{' . implode(',', $parts) . '}';
    }
    
    /**
     * Sets an array.
     * Unless a driver-specific method is used, this means simply serializing
     * the passed parameter and storing it as a string.
     * @param int $paramIndex
     * @param array $value
     * @return void
     * @see PreparedStatement::setArray()
     */
    function setArray($paramIndex, $value) 
    {
        if( $paramIndex > $this->positionsCount || $paramIndex < 1) {
            throw new SQLException('Cannot bind to invalid param index: '.$paramIndex);
        }
        if ($value === null)
            $this->setNull($paramIndex);
        else
            $this->boundInVars[$paramIndex] = "'" . $this->arrayToStr($value) . "'";        
    }

    /**
     * For setting value of Postgres BOOLEAN column.
     * @param int $paramIndex
     * @param boolean $value
     * @return void
     */
    function setBoolean($paramIndex, $value) 
    {
        if( $paramIndex > $this->positionsCount || $paramIndex < 1) {
            throw new SQLException('Cannot bind to invalid param index: '.$paramIndex);
        }        
        if ($value === null)
            $this->setNull($paramIndex);
        else
            $this->boundInVars[$paramIndex] = ($value ? "'t'" : "'f'");
    }

    /**
     * Applies sqlite_udf_encode_binary() to ensure that binary contents will be handled correctly by sqlite.
     * @param int $paramIndex
     * @param mixed $blob Blob object or string containing data.
     * @return void
     */
    function setBlob($paramIndex, $blob) 
    {    
        if ($blob === null) {
            $this->setNull($paramIndex);
        } else {
            // they took magic __toString() out of PHP5.0.0; this sucks
            if (is_object($blob)) {
                $blob = $blob->__toString();
            }            
            $this->boundInVars[$paramIndex] = "'" . pg_escape_bytea( $blob ) . "'";
        }    
        
    }
	
	/**
     * @param int $paramIndex
     * @param string $value
     * @return void
     */
    function setTime($paramIndex, $value) 
    {        
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if ( is_numeric ( $value ) ) {
	    	$value = date ( "H:i:s O", $value );
	    } elseif ( is_object ( $value ) ) {
	    	$value = date ( "H:i:s O", $value->getTime ( ) );
	    }
            $this->boundInVars [ $paramIndex ] = "'" . $this->escape ( $value ) . "'";
        }
    }
    
    /**
     * @param int $paramIndex
     * @param string $value
     * @return void
     */
    function setTimestamp($paramIndex, $value) 
    {        
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
       	    if (is_numeric($value)) $value = date('Y-m-d H:i:s O', $value);
       	    elseif (is_object($value)) $value = date("Y-m-d H:i:s O", $value->getTime());
            $this->boundInVars[$paramIndex] = "'".$this->escape($value)."'";
        }
    }
}
