<?php
// FIXME: this is unmaintainable, dont hardcode it, determine once what is available, then store somewhere
$core = array(
              array('name' => '', 'fullname' => 'BlockLayout', 'description' => 'Templating engine'),
              array('name' => 'XMLS', 'fullname' => 'Multi-Language', 'description' => 'The multi-language system and translation engine'),
              array('name' => 'creole', 'fullname' => 'CREOLE', 'description' => 'Database abstraction layer'),
              array('name' => 'installer', 'fullname' => 'Installer', 'description' => 'Product installer'),
              array('name' => 'privileges', 'fullname' => 'Privileges', 'description' => 'Privileges core modules'),
              array('name' => 'roles', 'fullname' => 'Roles', 'description' => 'Roles core module, manages users and groups'),
              array('name' => '', 'fullname' => 'Database', 'description' => 'Database structure / schema / layout'),
              array('name' => '', 'fullname' => 'Miscellaneous', 'description' => 'Other problems / issues'),
              array('name' => 'authsystem', 'fullname' => 'AuthSystem', 'description' => 'User Authentication System'),
              array('name' => 'dynamicdata', 'fullname' => 'DynamicData', 'description' => 'Dynamic Data Module'),
              array('name' => 'mail', 'fullname' => 'Mail', 'description' => 'Xaraya Mail Module'),
              array('name' => '', 'fullname' => 'API', 'description' => 'Application Programming Interface'),
              array('name' => 'themes', 'fullname' => 'Themes', 'description' => 'Themes Module'),
              array('name' => 'blocks', 'fullname' => 'Blocks', 'description' => 'Blocks core module'),
              array('name' => 'base', 'fullname' => 'Base', 'description' => 'Base core module'),
              array('name' => 'modules', 'fullname' => 'Modules', 'description' => 'Modules core module')
              );
$apps = array(
              array('name' => 'addressbook', 'fullname' => 'Addressbook', 'description' => 'Addressbook Module'),
              array('name' => 'articles', 'fullname' => 'Articles', 'description' => 'Articles Module'),
              array('name' => 'authinvision', 'fullname' => 'AuthInvision', 'description' => 'Invision Authentication Module'),
              array('name' => 'authldap', 'fullname' => 'AuthLDAP', 'description' => 'LDAP Authentication Module'),
              array('name' => 'authphpbb2', 'fullname' => 'AuthPHPBB2', 'description' => 'AuthPHPBB2 Module'),
              array('name' => 'authsso', 'fullname' => 'AuthSSO', 'description' => 'AuthSSO Module'),
              array('name' => 'authurl', 'fullname' => 'AuthURL', 'description' => 'AuthURL Module'),
              array('name' => 'autolinks', 'fullname' => 'Autolinks', 'description' => 'Autolinks Module'),
              array('name' => 'bbclick', 'fullname' => 'BBClick', 'description' => 'BBClick Module'),
              array('name' => 'bbcode', 'fullname' => 'BBCode', 'description' => 'BBCode Module'),
              array('name' => 'bkview', 'fullname' => 'BKView', 'description' => 'BitKeeper Interface Module'),
              array('name' => 'bloggerapi', 'fullname' => 'BloggerAPI', 'description' => 'Implementation of the Blogger 1.0 API http://plant.blogger.com/api/index.html'),
              array('name' => 'calendar', 'fullname' => 'Calendar', 'description' => 'Calendar Module'),
              array('name' => 'cast', 'fullname' => 'Cast', 'description' => 'Cast module'),
              array('name' => 'categories', 'fullname' => 'Categories', 'description' => 'Categories Module'),
              array('name' => 'censor', 'fullname' => 'Censor', 'description' => 'Censor Module'),
              array('name' => 'changelog', 'fullname' => 'ChangeLog', 'description' => 'changelog module'),
              array('name' => 'comments', 'fullname' => 'Comments', 'description' => 'Comments Module'),
              array('name' => 'contact', 'fullname' => 'Contact', 'description' => 'Contact Module'),
              array('name' => 'converter', 'fullname' => 'Converter', 'description' => 'Conversion of PostNuke and PHPNuke data and themes'),
              array('name' => 'courses', 'fullname' => 'Courses', 'description' => 'Courses Module'),
              array('name' => 'dyn_example', 'fullname' => 'Dyn_Example', 'description' => 'Example of a module which uses dynamic data to construct a
module'),
              array('name' => 'dynamic_planning', 'fullname' => 'Dynamic_Planning', 'description' => 'Dynamic planning module'),
              array('name' => 'edgar', 'fullname' => 'Edgar', 'description' => 'Edgar jabber status/reminder bot module'),
              array('name' => 'ephemerids', 'fullname' => 'Ephemerids', 'description' => 'Ephemerids Module'),
              array('name' => 'events', 'fullname' => 'Events', 'description' => 'Events modules'),
              array('name' => 'example', 'fullname' => 'Example', 'description' => 'Example module'),
              array('name' => 'facilities', 'fullname' => 'Facilities', 'description' => 'Facilities Module'),
              array('name' => 'figlet', 'fullname' => 'Figlet', 'description' => 'Figlet module'),
              array('name' => 'formcontrols', 'fullname' => 'Formcontrols', 'description' => 'Formcontrols module'),
              array('name' => 'headlines', 'fullname' => 'Headlines', 'description' => 'HeadLines Module'),
              array('name' => 'helpdesk', 'fullname' => 'helpdesk', 'description' => 'Helpdesk Module'),
              array('name' => 'hitcount', 'fullname' => 'Hitcount', 'description' => 'Hitcount Module'),
              array('name' => 'html', 'fullname' => 'HTML', 'description' => 'HTML Module'),
              array('name' => 'icalendar', 'fullname' => 'iCalendar', 'description' => 'iCalendar module'),
              array('name' => 'icecast', 'fullname' => 'Icecast', 'description' => 'Icecast module'),
              array('name' => 'imagefeed', 'fullname' => 'Imagefeed', 'description' => 'Imagefeed Module'),
              array('name' => 'issueareapub', 'fullname' => 'Issueareapub', 'description' => 'Issueareapub module'),
              array('name' => 'jabberstorage', 'fullname' => 'Jabberstorage', 'description' => 'Jabberstorage module'),
              array('name' => 'keywords', 'fullname' => 'Keywords', 'description' => 'Keywords Module'),
              array('name' => 'ledger', 'fullname' => 'Ledger', 'description' => 'Ledger module'),
              array('name' => 'messages', 'fullname' => 'Messages', 'description' => 'Messages Module'),
              array('name' => 'metaweblogapi', 'fullname' => 'MetaweBlogAPI', 'description' => 'Implementation of the metaweblog API'),
              array('name' => 'mime', 'fullname' => 'Mime', 'description' => 'Mime handling module'),
              array('name' => 'multisites', 'fullname' => 'Multisites', 'description' => 'Multisites module'),
              array('name' => 'mybookmarks', 'fullname' => 'MyBookmarks', 'description' => 'MyBookmarks module'),
              array('name' => 'nameday', 'fullname' => 'Nameday', 'description' => 'Nameday Module'),
              array('name' => 'nascar', 'fullname' => 'Nascar', 'description' => 'Nascar Module'),
              array('name' => 'newsgroups', 'fullname' => 'Newsgroups', 'description' => 'Newsgroups Module'),
              array('name' => 'opentracker', 'fullname' => 'OpenTracker', 'description' => 'OpenTracker Module'),
              array('name' => 'overlib', 'fullname' => 'Overlib', 'description' => 'Overlib utility module'),
              array('name' => 'paypalipn', 'fullname' => 'Paypalipn', 'description' => 'Paypal IPN module'),
              array('name' => 'paypalsetup', 'fullname' => 'Paypalsetup', 'description' => 'Paypal Setup module'),
              array('name' => 'photoshare', 'fullname' => 'Photoshare', 'description' => 'Photoshare module'),
              array('name' => 'phpldapadmin', 'fullname' => 'phpldapadmin', 'description' => 'PHP LDAP admin module'),
              array('name' => 'ping', 'fullname' => 'Ping', 'description' => 'Ping Module'),
              array('name' => 'polls', 'fullname' => 'Polls', 'description' => 'Polls Module'),
              array('name' => 'pubsub', 'fullname' => 'Pubsub', 'description' => 'Publish and Subscribe Engine'),
              array('name' => 'quotes', 'fullname' => 'Quotes', 'description' => 'Quotes Module'),
              array('name' => 'ratings', 'fullname' => 'Ratings', 'description' => 'Ratings Module'),
              array('name' => 'recommend', 'fullname' => 'Recommend', 'description' => 'Recommend module'),
              array('name' => 'referer', 'fullname' => 'Referer', 'description' => 'Referer Tracking Module'),
              array('name' => 'relations', 'fullname' => 'Relations', 'description' => 'Relations module'),
              array('name' => 'release', 'fullname' => 'Release', 'description' => 'Release Module'),
              array('name' => 'reports', 'fullname' => 'Reports', 'description' => 'Reports module'),
              array('name' => 'reviews', 'fullname' => 'Reviews', 'description' => 'Reviews module'),
              array('name' => 'scheduler', 'fullname' => 'Scheduler', 'description' => 'Scheduler module'),
              array('name' => 'school', 'fullname' => 'School', 'description' => 'School module'),
              array('name' => 'search', 'fullname' => 'Search', 'description' => 'Search module'),
              array('name' => 'shopping', 'fullname' => 'Shopping', 'description' => 'Shopping module'),
              array('name' => 'sitecloud', 'fullname' => 'Sitecloud', 'description' => 'Sitecloud module'),
              array('name' => 'sitetools', 'fullname' => 'Sitetools', 'description' => 'Sitetools Module'),
              array('name' => 'smilies', 'fullname' => 'Smilies', 'description' => 'Smilies Module'),
              array('name' => 'sniffer', 'fullname' => 'Sniffer', 'description' => 'Sniffer module'),
              array('name' => 'soapserver', 'fullname' => 'Soapserver', 'description' => 'Soapserver module'),
              array('name' => 'stats', 'fullname' => 'Stats', 'description' => 'Site Statistics Module'),
              array('name' => 'subitems', 'fullname' => 'Subitems', 'description' => 'Subitems module'),
              array('name' => 'tasks', 'fullname' => 'Tasks', 'description' => 'Tasks modules'),
              array('name' => 'timezone', 'fullname' => 'Timezone', 'description' => 'Timezone module'),
              array('name' => 'todolist', 'fullname' => 'Todolist', 'description' => 'ToDo List Module'),
              array('name' => 'trackback', 'fullname' => 'Trackback', 'description' => 'Trackback module'),
              array('name' => 'translations', 'fullname' => 'Translations', 'description' => 'Translations Module'),
              array('name' => 'uploads', 'fullname' => 'Uploads', 'description' => 'Uploads Module'),
              array('name' => 'userpoints', 'fullname' => 'Userpoints', 'description' => 'Userpoints modules'),
              array('name' => 'wiki', 'fullname' => 'Wiki', 'description' => 'Wiki Transform Module'),
              array('name' => 'window', 'fullname' => 'Window', 'description' => 'Window Module'),
              array('name' => 'workflow', 'fullname' => 'Workflow', 'description' => 'Workflow Module'),
              array('name' => 'wyomese', 'fullname' => 'Wyomese', 'description' => 'Wyomese module'),
              array('name' => 'xarbb', 'fullname' => 'XarBB', 'description' => 'XarBB Forum Module'),
              array('name' => 'xarcachemanager', 'fullname' => 'XarCacheManager', 'description' => 'Cache management module'),
              array('name' => 'xarldap', 'fullname' => 'XarLDAP', 'description' => 'XarLDAP module'),
              array('name' => 'xarlinkme', 'fullname' => 'XarLinkMe', 'description' => 'XarLinkMe module'),
              array('name' => 'xlink', 'fullname' => 'Xlink', 'description' => 'Xlink Module'),
              array('name' => 'xproject', 'fullname' => 'XProject', 'description' => 'XProject Module'),
              array('name' => 'xmlrpcserver', 'fullname' => 'xmlrpcserver', 'description' => 'XML RPC server'),
              array('name' => 'xmlrpcsystemapi', 'fullname' => 'XmlRpcSystemAPI', 'description' => 'Implementation of the xmlrpc system API http://xmlrpc.usefulinc.com/doc/reserved.html'),
              array('name' => 'xmlrpcvalidatorapi', 'fullname' => 'XmlRpcValidatorAPI', 'description' => 'Implementation of a XML-RPC validation API to test conformance of XML-RPC server to specifications Testable at http://validator.xmlrpc.com'),
              array('name' => 'xslt', 'fullname' => 'Xslt', 'description' => 'Xslt module')
              );
?>