<?php

function roles_admin_createmail()
{ 
    // TODO allow selection by group or user or all users.
    // Security check
    if (!xarSecurityCheck('MailRoles')) return;

    if (!xarVarFetch('uid', 'int:0:', $data['uid'], 0)) return;
	if (!xarVarFetch('groupuid', 'int:0:', $data['groupuid'],0)) return;
    if (!xarVarFetch('state', 'int:0:', $data['state'],0)) return;
    

    $data['authid'] = xarSecGenAuthKey(); 
    $data['groups'] = xarModAPIFunc('roles',
                                   	'user',
                                   	'getallgroups');
	if ($data['uid'] != 0) {
		$roles = new xarRoles();
	    $role = $roles->getRole($data['uid']);
	}
    
    // Return the output that has been generated by this function to BL
    return $data;
} 

?>