<?php

function roles_admin_createmail()
{ 
    // TODO allow selection by group or user or all users.
    // Security check
    if (!xarSecurityCheck('MailRoles')) return;

    if (!xarVarFetch('uid', 'int:1:', $uid)) return;

    $data['uid'] = $uid;
    $data['authid'] = xarSecGenAuthKey(); 
    // Return the output that has been generated by this function to BL
    return $data;
} 

?>