<?php

/**
 * @package core\exceptions
 * @subpackage exceptions
 * @category Xaraya Web Applications Framework
 * @version 2.4.0
 * @copyright see the html/credits.html file in this release
 * @license GPL {@link http://www.gnu.org/licenses/gpl.html}
 * @link http://www.xaraya.info
 */

// FIXME: this is unmaintainable, dont hardcode it, determine once what is available, then store somewhere
class xarComponents extends xarObject
{
    public static $core = [
        ['name' => '', 'fullname' => 'BlockLayout', 'description' => 'Templating engine'],
        ['name' => 'XMLS', 'fullname' => 'Multi-Language', 'description' => 'The multi-language system and translation engine'],
        ['name' => 'creole', 'fullname' => 'CREOLE', 'description' => 'Database abstraction layer'],
        ['name' => 'installer', 'fullname' => 'Installer', 'description' => 'Product installer'],
        ['name' => 'privileges', 'fullname' => 'Privileges', 'description' => 'Privileges core modules'],
        ['name' => 'roles', 'fullname' => 'Roles', 'description' => 'Roles core module, manages users and groups'],
        ['name' => '', 'fullname' => 'Database', 'description' => 'Database structure / schema / layout'],
        ['name' => '', 'fullname' => 'Miscellaneous', 'description' => 'Other problems / issues'],
        ['name' => 'authsystem', 'fullname' => 'AuthSystem', 'description' => 'User Authentication System'],
        ['name' => 'dynamicdata', 'fullname' => 'DynamicData', 'description' => 'Dynamic Data Module'],
        ['name' => 'mail', 'fullname' => 'Mail', 'description' => 'Xaraya Mail Module'],
        ['name' => '', 'fullname' => 'API', 'description' => 'Application Programming Interface'],
        ['name' => 'themes', 'fullname' => 'Themes', 'description' => 'Themes Module'],
        ['name' => 'blocks', 'fullname' => 'Blocks', 'description' => 'Blocks core module'],
        ['name' => 'base', 'fullname' => 'Base', 'description' => 'Base core module'],
        ['name' => 'modules', 'fullname' => 'Modules', 'description' => 'Modules core module'],
    ];
    public static $apps = [
        ['name' => 'addressbook', 'fullname' => 'Addressbook', 'description' => 'Addressbook Module'],
        ['name' => 'articles', 'fullname' => 'Articles', 'description' => 'Articles Module'],
        ['name' => 'authinvision', 'fullname' => 'AuthInvision', 'description' => 'Invision Authentication Module'],
        ['name' => 'authldap', 'fullname' => 'AuthLDAP', 'description' => 'LDAP Authentication Module'],
        ['name' => 'authphpbb2', 'fullname' => 'AuthPHPBB2', 'description' => 'AuthPHPBB2 Module'],
        ['name' => 'authsso', 'fullname' => 'AuthSSO', 'description' => 'AuthSSO Module'],
        ['name' => 'authurl', 'fullname' => 'AuthURL', 'description' => 'AuthURL Module'],
        ['name' => 'autolinks', 'fullname' => 'Autolinks', 'description' => 'Autolinks Module'],
        ['name' => 'bbclick', 'fullname' => 'BBClick', 'description' => 'BBClick Module'],
        ['name' => 'bbcode', 'fullname' => 'BBCode', 'description' => 'BBCode Module'],
        ['name' => 'bkview', 'fullname' => 'BKView', 'description' => 'BitKeeper Interface Module'],
        ['name' => 'bloggerapi', 'fullname' => 'BloggerAPI', 'description' => 'Implementation of the Blogger 1.0 API http://plant.blogger.com/api/index.html'],
        ['name' => 'calendar', 'fullname' => 'Calendar', 'description' => 'Calendar Module'],
        ['name' => 'cast', 'fullname' => 'Cast', 'description' => 'Cast module'],
        ['name' => 'categories', 'fullname' => 'Categories', 'description' => 'Categories Module'],
        ['name' => 'censor', 'fullname' => 'Censor', 'description' => 'Censor Module'],
        ['name' => 'changelog', 'fullname' => 'ChangeLog', 'description' => 'changelog module'],
        ['name' => 'comments', 'fullname' => 'Comments', 'description' => 'Comments Module'],
        ['name' => 'contact', 'fullname' => 'Contact', 'description' => 'Contact Module'],
        ['name' => 'converter', 'fullname' => 'Converter', 'description' => 'Conversion of PostNuke and PHPNuke data and themes'],
        ['name' => 'courses', 'fullname' => 'Courses', 'description' => 'Courses Module'],
        ['name' => 'dyn_example', 'fullname' => 'Dyn_Example', 'description' => 'Example of a module which uses dynamic data to construct a
module'],
        ['name' => 'dynamic_planning', 'fullname' => 'Dynamic_Planning', 'description' => 'Dynamic planning module'],
        ['name' => 'edgar', 'fullname' => 'Edgar', 'description' => 'Edgar jabber status/reminder bot module'],
        ['name' => 'ephemerids', 'fullname' => 'Ephemerids', 'description' => 'Ephemerids Module'],
        ['name' => 'events', 'fullname' => 'Events', 'description' => 'Events modules'],
        ['name' => 'example', 'fullname' => 'Example', 'description' => 'Example module'],
        ['name' => 'facilities', 'fullname' => 'Facilities', 'description' => 'Facilities Module'],
        ['name' => 'figlet', 'fullname' => 'Figlet', 'description' => 'Figlet module'],
        ['name' => 'formcontrols', 'fullname' => 'Formcontrols', 'description' => 'Formcontrols module'],
        ['name' => 'headlines', 'fullname' => 'Headlines', 'description' => 'HeadLines Module'],
        ['name' => 'helpdesk', 'fullname' => 'helpdesk', 'description' => 'Helpdesk Module'],
        ['name' => 'hitcount', 'fullname' => 'Hitcount', 'description' => 'Hitcount Module'],
        ['name' => 'html', 'fullname' => 'HTML', 'description' => 'HTML Module'],
        ['name' => 'icalendar', 'fullname' => 'iCalendar', 'description' => 'iCalendar module'],
        ['name' => 'icecast', 'fullname' => 'Icecast', 'description' => 'Icecast module'],
        ['name' => 'imagefeed', 'fullname' => 'Imagefeed', 'description' => 'Imagefeed Module'],
        ['name' => 'issueareapub', 'fullname' => 'Issueareapub', 'description' => 'Issueareapub module'],
        ['name' => 'jabberstorage', 'fullname' => 'Jabberstorage', 'description' => 'Jabberstorage module'],
        ['name' => 'keywords', 'fullname' => 'Keywords', 'description' => 'Keywords Module'],
        ['name' => 'ledger', 'fullname' => 'Ledger', 'description' => 'Ledger module'],
        ['name' => 'messages', 'fullname' => 'Messages', 'description' => 'Messages Module'],
        ['name' => 'metaweblogapi', 'fullname' => 'MetaweBlogAPI', 'description' => 'Implementation of the metaweblog API'],
        ['name' => 'mime', 'fullname' => 'Mime', 'description' => 'Mime handling module'],
        ['name' => 'multisites', 'fullname' => 'Multisites', 'description' => 'Multisites module'],
        ['name' => 'mybookmarks', 'fullname' => 'MyBookmarks', 'description' => 'MyBookmarks module'],
        ['name' => 'nameday', 'fullname' => 'Nameday', 'description' => 'Nameday Module'],
        ['name' => 'nascar', 'fullname' => 'Nascar', 'description' => 'Nascar Module'],
        ['name' => 'newsgroups', 'fullname' => 'Newsgroups', 'description' => 'Newsgroups Module'],
        ['name' => 'opentracker', 'fullname' => 'OpenTracker', 'description' => 'OpenTracker Module'],
        ['name' => 'overlib', 'fullname' => 'Overlib', 'description' => 'Overlib utility module'],
        ['name' => 'paypalipn', 'fullname' => 'Paypalipn', 'description' => 'Paypal IPN module'],
        ['name' => 'paypalsetup', 'fullname' => 'Paypalsetup', 'description' => 'Paypal Setup module'],
        ['name' => 'photoshare', 'fullname' => 'Photoshare', 'description' => 'Photoshare module'],
        ['name' => 'phpldapadmin', 'fullname' => 'phpldapadmin', 'description' => 'PHP LDAP admin module'],
        ['name' => 'ping', 'fullname' => 'Ping', 'description' => 'Ping Module'],
        ['name' => 'polls', 'fullname' => 'Polls', 'description' => 'Polls Module'],
        ['name' => 'pubsub', 'fullname' => 'Pubsub', 'description' => 'Publish and Subscribe Engine'],
        ['name' => 'quotes', 'fullname' => 'Quotes', 'description' => 'Quotes Module'],
        ['name' => 'ratings', 'fullname' => 'Ratings', 'description' => 'Ratings Module'],
        ['name' => 'recommend', 'fullname' => 'Recommend', 'description' => 'Recommend module'],
        ['name' => 'referer', 'fullname' => 'Referer', 'description' => 'Referer Tracking Module'],
        ['name' => 'relations', 'fullname' => 'Relations', 'description' => 'Relations module'],
        ['name' => 'release', 'fullname' => 'Release', 'description' => 'Release Module'],
        ['name' => 'reports', 'fullname' => 'Reports', 'description' => 'Reports module'],
        ['name' => 'reviews', 'fullname' => 'Reviews', 'description' => 'Reviews module'],
        ['name' => 'scheduler', 'fullname' => 'Scheduler', 'description' => 'Scheduler module'],
        ['name' => 'school', 'fullname' => 'School', 'description' => 'School module'],
        ['name' => 'search', 'fullname' => 'Search', 'description' => 'Search module'],
        ['name' => 'shopping', 'fullname' => 'Shopping', 'description' => 'Shopping module'],
        ['name' => 'sitecloud', 'fullname' => 'Sitecloud', 'description' => 'Sitecloud module'],
        ['name' => 'sitetools', 'fullname' => 'Sitetools', 'description' => 'Sitetools Module'],
        ['name' => 'smilies', 'fullname' => 'Smilies', 'description' => 'Smilies Module'],
        ['name' => 'sniffer', 'fullname' => 'Sniffer', 'description' => 'Sniffer module'],
        ['name' => 'soapserver', 'fullname' => 'Soapserver', 'description' => 'Soapserver module'],
        ['name' => 'stats', 'fullname' => 'Stats', 'description' => 'Site Statistics Module'],
        ['name' => 'subitems', 'fullname' => 'Subitems', 'description' => 'Subitems module'],
        ['name' => 'tasks', 'fullname' => 'Tasks', 'description' => 'Tasks modules'],
        ['name' => 'timezone', 'fullname' => 'Timezone', 'description' => 'Timezone module'],
        ['name' => 'todolist', 'fullname' => 'Todolist', 'description' => 'ToDo List Module'],
        ['name' => 'trackback', 'fullname' => 'Trackback', 'description' => 'Trackback module'],
        ['name' => 'translations', 'fullname' => 'Translations', 'description' => 'Translations Module'],
        ['name' => 'uploads', 'fullname' => 'Uploads', 'description' => 'Uploads Module'],
        ['name' => 'userpoints', 'fullname' => 'Userpoints', 'description' => 'Userpoints modules'],
        ['name' => 'wiki', 'fullname' => 'Wiki', 'description' => 'Wiki Transform Module'],
        ['name' => 'window', 'fullname' => 'Window', 'description' => 'Window Module'],
        ['name' => 'workflow', 'fullname' => 'Workflow', 'description' => 'Workflow Module'],
        ['name' => 'wyomese', 'fullname' => 'Wyomese', 'description' => 'Wyomese module'],
        ['name' => 'xarbb', 'fullname' => 'XarBB', 'description' => 'XarBB Forum Module'],
        ['name' => 'cachemanager', 'fullname' => 'XarCacheManager', 'description' => 'Cache management module'],
        ['name' => 'xarldap', 'fullname' => 'XarLDAP', 'description' => 'XarLDAP module'],
        ['name' => 'xarlinkme', 'fullname' => 'XarLinkMe', 'description' => 'XarLinkMe module'],
        ['name' => 'xlink', 'fullname' => 'Xlink', 'description' => 'Xlink Module'],
        ['name' => 'xproject', 'fullname' => 'XProject', 'description' => 'XProject Module'],
        ['name' => 'xmlrpcserver', 'fullname' => 'xmlrpcserver', 'description' => 'XML RPC server'],
        ['name' => 'xmlrpcsystemapi', 'fullname' => 'XmlRpcSystemAPI', 'description' => 'Implementation of the xmlrpc system API http://xmlrpc.usefulinc.com/doc/reserved.html'],
        ['name' => 'xmlrpcvalidatorapi', 'fullname' => 'XmlRpcValidatorAPI', 'description' => 'Implementation of a XML-RPC validation API to test conformance of XML-RPC server to specifications Testable at http://validator.xmlrpc.com'],
        ['name' => 'xslt', 'fullname' => 'Xslt', 'description' => 'Xslt module'],
    ];
}
